backend:
  name: git-gateway
  branch: main
media_folder: public/img
public_folder: img
publish_mode: editorial_workflow
slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "-"
collections:  
  - name: sponsors 
    label: "Sponsors"
    folder: "content/sponsors/{{year}}"
    identifier_field: name
    format: json
    preview_path: "content/sponsors/{{year}}/{{name}}"
    fields: # The fields for each document, usually in front matter
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Sponsor Date", name: "date", widget: "datetime"}
      - {label: "Logo", name: "logo", widget: "image"}
      - {label: "Description", name: "description", widget: "markdown"}
  - label: "Pages"
    name: "pages"
    files:
      - label: "Home Page"
        name: "index"
        file: "content/index.mdx"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Intro, name: intro, widget: markdown}
  - label: "Posts"
    name: "post"
    folder: "content/posts"
    create: true
    extension: "mdx"
    format: "frontmatter"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}